### ISSUE TITLE
Error handling and refactoring in translations_ns.py

### ISSUE THREAD

**Issue by ClaudeMeier** [PythonDataScience24/E-Lang#2]
Error Handling in generate_sentences Function:

The function generate_sentences does not handle the case where the API response does not contain the expected data structure. This can lead to runtime errors if the API response is not as expected.
try:
        req = requests.get(url)
        req.raise_for_status()  # Raise an HTTPError for bad responses
        req_parsed = req.json()
        first_sentence = req_parsed['results'][0]
        target_text = first_sentence['text']
        translation_categories = first_sentence['translations']
        for category in translation_categories:
            if len(category) != 0:
                for translation in category:
                    if len(translation) != 0:
                        source_text = translation['text']
        return target_text, source_text
    except (requests.RequestException, KeyError, IndexError) as e:
        return None, None  # Handle the error as needed
        
Redundant Code in SentenceGenerator and Translations Resources:

The SentenceGenerator and Translations resources have almost identical code for generating sentences and creating gap sentences. This redundancy can be avoided by refactoring the common logic into a separate helper function.

def generate_translation_data():
    translation, english_sentence = generate_sentences()
    if not translation or not english_sentence:
        return None  # Handle the error as needed
    gap_sentence, correct_word = create_gap_sentence(translation)
    return {
        'english_sentence': english_sentence,
        'german_sentence': gap_sentence,
        'correct_word': correct_word
    }

@translations_ns.route('/generate_sentence')
class SentenceGenerator(Resource):
    def get(self):
        data = generate_translation_data()
        if data is None:
            return {"message": "Error generating sentence"}, 500
        return jsonify(data)

@translations_ns.route('/translations')
class Translations(Resource):
    @translations_ns.expect(translations_model)
    @translations_ns.marshal_with(translations_model)
    def get(self):
        data = generate_translation_data()
        if data is None:
            return {"message": "Error generating sentence"}, 500
        return data

**Comment by Newton001** [comment]
Two approaches were utilized
