### ISSUE TITLE
General Suggestions to Documentation, Testing, Code Quality, Error Handling

### ISSUE THREAD

**Issue by oiUniBe** [PythonDataScience24/E-Lang#3]
Documentation:
    Add comprehensive docstrings for all methods and classes to improve code readability and maintainability. Docstrings should include information about what each method does, its parameters, return values, and any exceptions it might raise.

Testing:
    Move test cases to a dedicated testing framework such as pytest or unittest to ensure systematic testing of all components.
    Ensure test coverage for edge cases and handle scenarios such as invalid inputs, boundary conditions, and error paths.

Code Quality:
    Utilize linters like pylint or flake8 to maintain code quality and consistency. These tools can help identify potential issues, enforce coding standards, and improve overall code readability.
    Follow PEP 8 guidelines for code formatting, including consistent indentation, naming conventions, and line lengths.

Error Handling:
    Implement more robust error handling mechanisms, especially around user inputs and file I/O operations.
    Validate user inputs to prevent common security vulnerabilities such as SQL injection or XSS attacks.
    Use try-except blocks to catch and handle exceptions gracefully, providing meaningful error messages to users.

These snippets demonstrate how you can incorporate improvements in documentation, testing, code quality, and error handling into your backend codebase.
Documentation:
class LanguageModel(db.Model):
    """Model representing a language entry in the database."""
    def __init__(self, word, translation, sentence, difficulty):
        """
        Initialize a LanguageModel object.
        
        Args:
            word (str): The word in the original language.
            translation (str): The translation of the word.
            sentence (str): Example sentence using the word.
            difficulty (int): Difficulty level of the word.
        """
        self.word = word
        self.translation = translation
        self.sentence = sentence
        self.difficulty = difficulty

    def save_to_db(self):
        """
        Save the LanguageModel object to the database.
        """
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self):
        """
        Delete the LanguageModel object from the database.
        """
        db.session.delete(self)
        db.session.commit()

Testing:
import unittest
from models import LanguageModel

class TestLanguageModel(unittest.TestCase):
    def test_save_to_db(self):
        word = 'hello'
        translation = 'hola'
        sentence = 'Hello, how are you?'
        difficulty = 1
        language_entry = LanguageModel(word, translation, sentence, difficulty)
        language_entry.save_to_db()
        
        # Add assertions to verify that the entry was saved successfully

    def test_delete_from_db(self):
        # Similar test cases for delete_from_db method
        pass

if __name__ == '__main__':
    unittest.main()

Error Handling:
@language_ns.route('/languagemodel')
class LanguagesResource(Resource):
    @language_ns.marshal_list_with(language_model)
    def get(self):
        """Get All words and information from database"""
        try:
            all_words = LanguageModel.query.all()
            return all_words
        except Exception as e:
            return {"message": "An error occurred while fetching data"}, 500
    
    @language_ns.marshal_with(language_model)
    @language_ns.expect(language_model)
    def post(self):
        """Create a new word selection"""
        try:
            data = request.get_json()
            new_words = LanguageModel(
                word=data.get("word"),
                translation=data.get("translation"),
                sentence=data.get("sentence"),
                difficulty=data.get("difficulty")
            )
            new_words.save_to_db()
            return new_words, 201
        except Exception as e:
            return {"message": "An error occurred while creating a new word selection"}, 500

**Comment by Newton001** [comment]
Modified the api
